env:
  browser: true
  es6: true
  node: true
  mocha: true

globals:
  angular: 1
  
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
