# References for later use in the yaml.
_anchors:
  labels:
    - &label-security
      name: "security" 
      color: "ff0000"
    - &label-docs
      name: "docs"
      color: "ffff00"



# Configuration
endpoint:
  port: 3000 # application port
session: # defaults to local session storage, if 'redis' is not configured
  secret: keyboard cat # please change this :)
  redis: # for configuration options see https://github.com/tj/connect-redis#options
    host: localhost
    port: 4500 # 6379
    ttl: 30000
    logErrors: true


github:
  oauth: # GitHub App OAuth settings
    id: 
    secret: 
  appId:  # github app id
  keyFile: github-app.pem
  base: http://localhost:6000 # https://api.github.com

template:

  repo:
    default:
      name: "Default"
      pattern: "^[A-Za-z\\-_]+$" # repository name pattern
      config: &default-repo
        private: false
        has_issues: true
        has_projects: false
        has_wiki: true
        allow_squash_merge: true
        allow_merge_commit: true
        allow_rebase_merge: true
        auto_init: true # is required to be true; otherwise no branch settings can be applied
        gitignore_template: "Gradle" # see https://github.com/github/gitignore
      label:
        - *label-security
        - *label-docs
    private:
      name: "Private Repository"
      config:
        <<: *default-repo
        private: true
      label:
        - *label-docs
    
  branch:
    none:
      name: "None"
      branch: null
      config: null
    default:
      name: "Protect Master"
      branch: "master"
      config: &default-branch
        required_status_checks:
          # branches need to be up to date
          strict: true
          contexts: []
        required_pull_request_reviews:
          dismiss_stale_reviews: true
        enforce_admins:
        restrictions:


  